
#TENSORFLOW



In [2]:
import tensorflow as tf
import numpy as np

In [3]:
a = tf.constant(15)
b = tf.constant(20)
print(a+b)

tf.Tensor(35, shape=(), dtype=int32)


In [4]:
# input
x = np.random.rand(100).astype(np.float32)
print(x)

[0.8504713  0.85452175 0.3315653  0.38671535 0.25500506 0.20998606
 0.8750968  0.48433083 0.5358115  0.21780618 0.3076208  0.7006341
 0.5842766  0.8038196  0.11357661 0.4299451  0.19184439 0.37173545
 0.80373603 0.5568989  0.8837019  0.31298107 0.37957606 0.64465934
 0.3531142  0.2527034  0.86014074 0.33630422 0.95643723 0.7247691
 0.2302004  0.9282331  0.89376485 0.46210495 0.8914851  0.91536963
 0.06706006 0.41773865 0.4422333  0.8734292  0.1432331  0.38060734
 0.9992029  0.53125215 0.8804735  0.97201335 0.42790917 0.07302125
 0.86070424 0.6006975  0.27666435 0.24202025 0.60974735 0.96029663
 0.21613714 0.25620517 0.3577765  0.46330142 0.65488786 0.9669094
 0.38426858 0.8455017  0.571291   0.2316837  0.4746284  0.532473
 0.68602586 0.25758648 0.15257671 0.56874883 0.8261637  0.29155162
 0.6756336  0.251554   0.95196843 0.5356058  0.9867703  0.3835229
 0.01902482 0.48618013 0.57940936 0.077378   0.7744604  0.36828107
 0.69179034 0.27438506 0.89703995 0.9744103  0.35418773 0.5408589
 0

In [5]:
# output - observed
y = x * 0.2 + 0.2
# Weight
W = tf.Variable(tf.random.normal([1]))
# bias
b = tf.Variable(tf.zeros([1]))

In [8]:
# Create a function for MSE - mean squared error
def mse_loss():
  ypred = W * x + b
  loss = tf.reduce_mean(tf.square(ypred-y))
  return loss

In [9]:
# Optimizer
optimizer = tf.keras.optimizers.Adam()

In [11]:
# Iterations
for step in range(5000):
  optimizer.minimize(mse_loss,var_list=[W,b])
  if step % 500 == 0:
    print(step, W.numpy(), b.numpy())

0 [0.0227623] [0.00099999]
500 [0.21035466] [0.1930387]
1000 [0.20595092] [0.19666514]
1500 [0.20232867] [0.19869505]
2000 [0.2006308] [0.1996465]
2500 [0.20010844] [0.19993925]
3000 [0.20001055] [0.19999397]
3500 [0.2000014] [0.19999918]
4000 [0.20000108] [0.19999938]
4500 [0.2000008] [0.19999954]


#KERAS

In [12]:
# Step 1 - Load the dataset
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

INPUT Variables
x1 - Number of times pregnant
x2 - plasma glucose
x3 - diastolic blood pressure
x4 - Triceps skin fold thickness
x5 - 2-hour serum insulin
x6 - bmi
x7 - diabetes pedigree function
x8 - age (yrs)
Output Variable ##
Class Variable - 0 or 1

In [15]:
import numpy
dataset = numpy.loadtxt('/content/pima-indians-diabetes.csv',delimiter=',',skiprows=1)
dataset

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [16]:
x = dataset[:,0:8]
print(type(x))
print(x.shape)
y = dataset[:,8]
print(y)

<class 'numpy.ndarray'>
(768, 8)
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0.
 1. 0. 1. 0. 0. 1.

Step 2 - Creating or define the Keras Model
Sequential Model
Layer1 -> Layer2 -> Layer3

In [17]:
model = Sequential()

The model expects row of data with 8 variables
12 = nodes

In [18]:
model.add(Dense(12, input_shape=(8,), activation='relu'))

Hidden Layer
8 = nodes

In [19]:
model.add(Dense(8, activation='relu'))

In [20]:
# Output layer
model.add(Dense(1,activation='sigmoid'))

Step 3 - Compile the Keras model
loss (error)
optimizer (adam)
metrics = accuracy

In [21]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Step 4 - Fit / Train the model
1 = Epochs - number of iterations / passes
2 - Batch - sample data

In [23]:
model.fit(x,y, epochs=50, batch_size=10)

Epoch 1/50
77/77 [==============================] - 0s 3ms/step - loss: 0.4726 - accuracy: 0.7656
Epoch 2/50
77/77 [==============================] - 0s 2ms/step - loss: 0.4795 - accuracy: 0.7708
Epoch 3/50
77/77 [==============================] - 0s 2ms/step - loss: 0.4761 - accuracy: 0.7760
Epoch 4/50
77/77 [==============================] - 0s 2ms/step - loss: 0.4752 - accuracy: 0.7669
Epoch 5/50
77/77 [==============================] - 0s 2ms/step - loss: 0.4884 - accuracy: 0.7695
Epoch 6/50
77/77 [==============================] - 0s 2ms/step - loss: 0.4671 - accuracy: 0.7695
Epoch 7/50
77/77 [==============================] - 0s 2ms/step - loss: 0.4784 - accuracy: 0.7734
Epoch 8/50
77/77 [==============================] - 0s 2ms/step - loss: 0.4829 - accuracy: 0.7565
Epoch 9/50
77/77 [==============================] - 0s 2ms/step - loss: 0.4748 - accuracy: 0.7682
Epoch 10/50
77/77 [==============================] - 0s 2ms/step - loss: 0.4661 - accuracy: 0.7747
Epoch 11/50
77/77 [

Step 5 - evaluate the model

In [24]:
model.evaluate(x,y)

24/24 [==============================] - 0s 2ms/step - loss: 0.4709 - accuracy: 0.7682


[0.4709261655807495, 0.7682291865348816]

#THEANO

In [25]:
import theano
from theano import *
import theano.tensor as T
import numpy as np
import pandas as pd
from theano import function

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.8 MB 5.1 MB/s 
  Created wheel for theano: filename=Theano-1.0.5-py3-none-any.whl size=2668111 sha256=ca5a29a4ba871ecd8b45315bd2bd1534f46d5d296630cefcb454a85c22114f3d
  Stored in directory: /root/.cache/pip/wheels/26/68/6f/745330367ce7822fe0cd863712858151f5723a0a5e322cc144
Successfully built theano


In [26]:
# scalar variables
v1 = T.dscalar()
v2 = T.scalar()
# subtraction
sres = v1-v2

In [28]:
#add
ares = v1+v2
#convert the results into functions
calcsres = theano.function([v1,v2],sres)
calcares = theano.function([v1,v2],ares)
calcares(12,23)
calcsres(13,12)
x = T.dmatrix('x')
y = T.dmatrix('y')

In [29]:
z = x+y
func = function([x,y],z)
m1 = [
[1,2],
[3,4]
]
m2 = [
[4,5],
[6,7]
]
func(m1,m2)

array([[ 5.,  7.],
       [ 9., 11.]])

#Pytorch

In [30]:
import torch
import numpy as np

### 1 - using data

In [31]:
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)

In [32]:
print(type(x_data))

<class 'torch.Tensor'>


### 2 - using numpy array

In [33]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


### 3 - using another tensor

In [34]:
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

One Tensor: 
 tensor([[1, 1],
        [1, 1]])
tensor([[0.1233, 0.5974],
        [0.5984, 0.7637]])


#### more ways to create tensors

In [35]:
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))
tensor = torch.rand(3,4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device

tensor([[0.9378, 0.5080, 0.9005],
        [0.3791, 0.8897, 0.5984]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.3468, 0.8177, 0.0115, 0.2408],
        [0.7795, 0.7669, 0.6804, 0.4550],
        [0.9616, 0.3821, 0.9734, 0.5598]])


device(type='cpu')

# Tensor Operations

In [37]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("Device tensor is stored in ", tensor.device)

###Indexing, Slicing

In [38]:
tensor = torch.ones(4,4)
print(tensor)
print(tensor)
tensor1 = torch.zeros(4,4)
print(tensor1)
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)
# Multiply Operation
tensor.mul(tensor1)
tensor * tensor1
tensor.T
# inplace - change the original tensor
tensor.add_(3)
print(tensor)
# from tensor to numpy
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
